# $Id: Makefile.win,v 1.2 2006-12-19 21:51:32 carregal Exp $

LUA_DIR= c:\lua51\lua

LUAS= src\logging\console.lua src\logging\email.lua src\logging\file.lua src\logging\logging.lua src\logging\socket.lua src\logging\sql.lua

build clean:

install:
	IF NOT EXIST $(LUA_DIR)\logging mkdir $(LUA_DIR)\logging
	FOR %i IN ($(LUAS)) DO copy %i $(LUA_DIR)\logging
